query favorites {
  me {
    favorites {
      id
      title
      slug
      category {
        name
      }
      icon {
        fixed(width: 50, height: 50) {
          base64
          width
          height
          src
          srcSet
          srcWebp
          srcSetWebp
        }
        fluid(maxWidth: 200) {
          base64
          aspectRatio
          src
          srcSet
          srcWebp
          srcSetWebp
          sizes
        }
      }
    }
  }
}
